### ISSUE TITLE
A Question on Re-Sampling

### ISSUE THREAD

**Issue by TerenceLiu98** [nurahmadi/Stroke-prediction-with-ML#1]
Hi! Nice work on Stroke prediction!

I am curious on whether you have consider that it is not proper that using SMOTE on the testing set, since the interpolation generate some "fake" datapoints, is there possible that the model you train just classify those generated data instead of the real data?

**Comment by nurahmadi** [comment]
Thanks for identifying this issue. I forgot to consider it when making this repo a while ago. I'll try to revise the codes when I have time (as currently I'm quite busy). Basically, we have to split the data first into training and testing set, then apply SMOTE on the training set only. We can then evaluate the model on the testing set (which is free from interpolated/synthetic values).

**Comment by TerenceLiu98** [comment]
Yes that make sense. Again, very nice try for over-sampling method in imbalanced data, this code helps me a lot! 👍
